import io
import markdown
import logging
from app.services.pdf_rendering import render_html_to_pdf_bytes

logger = logging.getLogger(__name__)

def generate_report_pdf(title: str, markdown_content: str) -> io.BytesIO:
    """Generate a PDF from markdown content."""
    
    # Convert Markdown to HTML
    html_content = markdown.markdown(
        markdown_content,
        extensions=["fenced_code", "tables", "sane_lists", "nl2br"]
    )
    
    # Wrap in our styling template
    full_html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <title>{title}</title>
        <style>
            @page {{
                size: letter portrait;
                margin: 2cm;
                @frame header_frame {{
                    -pdf-frame-content: header_content;
                    left: 50pt; width: 512pt; top: 30pt; height: 40pt;
                }}
                @frame footer_frame {{
                    -pdf-frame-content: footer_content;
                    left: 50pt; width: 512pt; top: 760pt; height: 20pt;
                }}
            }}
            body {{
                font-family: Helvetica, Arial, sans-serif;
                font-size: 11pt;
                line-height: 1.5;
                color: #333333;
            }}
            h1 {{
                font-size: 22pt;
                color: #111827;
                border-bottom: 2px solid #e5e7eb;
                padding-bottom: 8px;
                margin-bottom: 16px;
            }}
            h2 {{
                font-size: 16pt;
                color: #374151;
                margin-top: 24px;
                margin-bottom: 12px;
            }}
            h3 {{
                font-size: 14pt;
                color: #4b5563;
                margin-top: 20px;
                margin-bottom: 8px;
            }}
            p {{
                margin-bottom: 12px;
            }}
            hr {{
                border: 0;
                border-top: 1px solid #e5e7eb;
                margin: 20px 0;
            }}
            strong {{
                font-weight: bold;
                color: #111827;
            }}
        </style>
    </head>
    <body>
        <div id="header_content">
            <div style="color: #6b7280; font-size: 9pt; text-align: right;">SiraFit Report</div>
        </div>
        
        <h1>{title}</h1>
        
        {html_content}
        
        <div id="footer_content">
            <div style="text-align: center; font-size: 9pt; color: #9ca3af;">
                Generated by SiraFit - Page <pdf:pagenumber> of <pdf:pagecount>
            </div>
        </div>
    </body>
    </html>
    """
    
    return render_html_to_pdf_bytes(full_html)
