/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppResumesRouteImport } from './routes/_app.resumes'
import { Route as AppRankingRouteImport } from './routes/_app.ranking'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppMatchRouteImport } from './routes/_app.match'
import { Route as AppJobsRouteImport } from './routes/_app.jobs'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCoverLettersRouteImport } from './routes/_app.cover-letters'
import { Route as AppBatchRouteImport } from './routes/_app.batch'
import { Route as AppApplicationsRouteImport } from './routes/_app.applications'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppSettingsIndexRouteImport } from './routes/_app.settings.index'
import { Route as AppResumesIndexRouteImport } from './routes/_app.resumes.index'
import { Route as AppJobsIndexRouteImport } from './routes/_app.jobs.index'
import { Route as AppCoverLettersIndexRouteImport } from './routes/_app.cover-letters.index'
import { Route as AppApplicationsIndexRouteImport } from './routes/_app.applications.index'
import { Route as AppAnalyticsIndexRouteImport } from './routes/_app.analytics.index'
import { Route as AppSettingsResumeRouteImport } from './routes/_app.settings.resume'
import { Route as AppSettingsPrivacyRouteImport } from './routes/_app.settings.privacy'
import { Route as AppSettingsNotificationsRouteImport } from './routes/_app.settings.notifications'
import { Route as AppSettingsAiRouteImport } from './routes/_app.settings.ai'
import { Route as AppResumesProfilesRouteImport } from './routes/_app.resumes.profiles'
import { Route as AppResumesProfileEditorRouteImport } from './routes/_app.resumes.profile-editor'
import { Route as AppResumesBuilderRouteImport } from './routes/_app.resumes.builder'
import { Route as AppResumesIdRouteImport } from './routes/_app.resumes.$id'
import { Route as AppJobsImportRouteImport } from './routes/_app.jobs.import'
import { Route as AppJobsHistoryRouteImport } from './routes/_app.jobs.history'
import { Route as AppJobsJobIdRouteImport } from './routes/_app.jobs.$jobId'
import { Route as AppCoverLettersBuilderRouteImport } from './routes/_app.cover-letters.builder'
import { Route as AppBatchIdRouteImport } from './routes/_app.batch.$id'
import { Route as AppApplicationsTimelineRouteImport } from './routes/_app.applications.timeline'
import { Route as AppApplicationsFollowupsRouteImport } from './routes/_app.applications.followups'
import { Route as AppApplicationsIdRouteImport } from './routes/_app.applications.$id'
import { Route as AppAnalyticsSkillsRouteImport } from './routes/_app.analytics.skills'
import { Route as AppAnalyticsMarketRouteImport } from './routes/_app.analytics.market'
import { Route as AppResumesIdEditorRouteImport } from './routes/_app.resumes.$id.editor'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppResumesRoute = AppResumesRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingRoute = AppRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchRoute = AppMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCoverLettersRoute = AppCoverLettersRouteImport.update({
  id: '/cover-letters',
  path: '/cover-letters',
  getParentRoute: () => AppRoute,
} as any)
const AppBatchRoute = AppBatchRouteImport.update({
  id: '/batch',
  path: '/batch',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppResumesIndexRoute = AppResumesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppResumesRoute,
} as any)
const AppJobsIndexRoute = AppJobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppJobsRoute,
} as any)
const AppCoverLettersIndexRoute = AppCoverLettersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCoverLettersRoute,
} as any)
const AppApplicationsIndexRoute = AppApplicationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppApplicationsRoute,
} as any)
const AppAnalyticsIndexRoute = AppAnalyticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAnalyticsRoute,
} as any)
const AppSettingsResumeRoute = AppSettingsResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsPrivacyRoute = AppSettingsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsAiRoute = AppSettingsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppResumesProfilesRoute = AppResumesProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AppResumesRoute,
} as any)
const AppResumesProfileEditorRoute = AppResumesProfileEditorRouteImport.update({
  id: '/profile-editor',
  path: '/profile-editor',
  getParentRoute: () => AppResumesRoute,
} as any)
const AppResumesBuilderRoute = AppResumesBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AppResumesRoute,
} as any)
const AppResumesIdRoute = AppResumesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppResumesRoute,
} as any)
const AppJobsImportRoute = AppJobsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppJobsRoute,
} as any)
const AppJobsHistoryRoute = AppJobsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppJobsRoute,
} as any)
const AppJobsJobIdRoute = AppJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => AppJobsRoute,
} as any)
const AppCoverLettersBuilderRoute = AppCoverLettersBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AppCoverLettersRoute,
} as any)
const AppBatchIdRoute = AppBatchIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppBatchRoute,
} as any)
const AppApplicationsTimelineRoute = AppApplicationsTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppApplicationsRoute,
} as any)
const AppApplicationsFollowupsRoute =
  AppApplicationsFollowupsRouteImport.update({
    id: '/followups',
    path: '/followups',
    getParentRoute: () => AppApplicationsRoute,
  } as any)
const AppApplicationsIdRoute = AppApplicationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppApplicationsRoute,
} as any)
const AppAnalyticsSkillsRoute = AppAnalyticsSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppAnalyticsRoute,
} as any)
const AppAnalyticsMarketRoute = AppAnalyticsMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AppAnalyticsRoute,
} as any)
const AppResumesIdEditorRoute = AppResumesIdEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AppResumesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/analytics': typeof AppAnalyticsRouteWithChildren
  '/applications': typeof AppApplicationsRouteWithChildren
  '/batch': typeof AppBatchRouteWithChildren
  '/cover-letters': typeof AppCoverLettersRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/jobs': typeof AppJobsRouteWithChildren
  '/match': typeof AppMatchRoute
  '/notifications': typeof AppNotificationsRoute
  '/ranking': typeof AppRankingRoute
  '/resumes': typeof AppResumesRouteWithChildren
  '/settings': typeof AppSettingsRouteWithChildren
  '/analytics/market': typeof AppAnalyticsMarketRoute
  '/analytics/skills': typeof AppAnalyticsSkillsRoute
  '/applications/$id': typeof AppApplicationsIdRoute
  '/applications/followups': typeof AppApplicationsFollowupsRoute
  '/applications/timeline': typeof AppApplicationsTimelineRoute
  '/batch/$id': typeof AppBatchIdRoute
  '/cover-letters/builder': typeof AppCoverLettersBuilderRoute
  '/jobs/$jobId': typeof AppJobsJobIdRoute
  '/jobs/history': typeof AppJobsHistoryRoute
  '/jobs/import': typeof AppJobsImportRoute
  '/resumes/$id': typeof AppResumesIdRouteWithChildren
  '/resumes/builder': typeof AppResumesBuilderRoute
  '/resumes/profile-editor': typeof AppResumesProfileEditorRoute
  '/resumes/profiles': typeof AppResumesProfilesRoute
  '/settings/ai': typeof AppSettingsAiRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/privacy': typeof AppSettingsPrivacyRoute
  '/settings/resume': typeof AppSettingsResumeRoute
  '/analytics/': typeof AppAnalyticsIndexRoute
  '/applications/': typeof AppApplicationsIndexRoute
  '/cover-letters/': typeof AppCoverLettersIndexRoute
  '/jobs/': typeof AppJobsIndexRoute
  '/resumes/': typeof AppResumesIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/resumes/$id/editor': typeof AppResumesIdEditorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/batch': typeof AppBatchRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/match': typeof AppMatchRoute
  '/notifications': typeof AppNotificationsRoute
  '/ranking': typeof AppRankingRoute
  '/analytics/market': typeof AppAnalyticsMarketRoute
  '/analytics/skills': typeof AppAnalyticsSkillsRoute
  '/applications/$id': typeof AppApplicationsIdRoute
  '/applications/followups': typeof AppApplicationsFollowupsRoute
  '/applications/timeline': typeof AppApplicationsTimelineRoute
  '/batch/$id': typeof AppBatchIdRoute
  '/cover-letters/builder': typeof AppCoverLettersBuilderRoute
  '/jobs/$jobId': typeof AppJobsJobIdRoute
  '/jobs/history': typeof AppJobsHistoryRoute
  '/jobs/import': typeof AppJobsImportRoute
  '/resumes/$id': typeof AppResumesIdRouteWithChildren
  '/resumes/builder': typeof AppResumesBuilderRoute
  '/resumes/profile-editor': typeof AppResumesProfileEditorRoute
  '/resumes/profiles': typeof AppResumesProfilesRoute
  '/settings/ai': typeof AppSettingsAiRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/privacy': typeof AppSettingsPrivacyRoute
  '/settings/resume': typeof AppSettingsResumeRoute
  '/analytics': typeof AppAnalyticsIndexRoute
  '/applications': typeof AppApplicationsIndexRoute
  '/cover-letters': typeof AppCoverLettersIndexRoute
  '/jobs': typeof AppJobsIndexRoute
  '/resumes': typeof AppResumesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/resumes/$id/editor': typeof AppResumesIdEditorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_app/analytics': typeof AppAnalyticsRouteWithChildren
  '/_app/applications': typeof AppApplicationsRouteWithChildren
  '/_app/batch': typeof AppBatchRouteWithChildren
  '/_app/cover-letters': typeof AppCoverLettersRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/jobs': typeof AppJobsRouteWithChildren
  '/_app/match': typeof AppMatchRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/ranking': typeof AppRankingRoute
  '/_app/resumes': typeof AppResumesRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/analytics/market': typeof AppAnalyticsMarketRoute
  '/_app/analytics/skills': typeof AppAnalyticsSkillsRoute
  '/_app/applications/$id': typeof AppApplicationsIdRoute
  '/_app/applications/followups': typeof AppApplicationsFollowupsRoute
  '/_app/applications/timeline': typeof AppApplicationsTimelineRoute
  '/_app/batch/$id': typeof AppBatchIdRoute
  '/_app/cover-letters/builder': typeof AppCoverLettersBuilderRoute
  '/_app/jobs/$jobId': typeof AppJobsJobIdRoute
  '/_app/jobs/history': typeof AppJobsHistoryRoute
  '/_app/jobs/import': typeof AppJobsImportRoute
  '/_app/resumes/$id': typeof AppResumesIdRouteWithChildren
  '/_app/resumes/builder': typeof AppResumesBuilderRoute
  '/_app/resumes/profile-editor': typeof AppResumesProfileEditorRoute
  '/_app/resumes/profiles': typeof AppResumesProfilesRoute
  '/_app/settings/ai': typeof AppSettingsAiRoute
  '/_app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/_app/settings/privacy': typeof AppSettingsPrivacyRoute
  '/_app/settings/resume': typeof AppSettingsResumeRoute
  '/_app/analytics/': typeof AppAnalyticsIndexRoute
  '/_app/applications/': typeof AppApplicationsIndexRoute
  '/_app/cover-letters/': typeof AppCoverLettersIndexRoute
  '/_app/jobs/': typeof AppJobsIndexRoute
  '/_app/resumes/': typeof AppResumesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/resumes/$id/editor': typeof AppResumesIdEditorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/logout'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/verify-email'
    | '/analytics'
    | '/applications'
    | '/batch'
    | '/cover-letters'
    | '/dashboard'
    | '/jobs'
    | '/match'
    | '/notifications'
    | '/ranking'
    | '/resumes'
    | '/settings'
    | '/analytics/market'
    | '/analytics/skills'
    | '/applications/$id'
    | '/applications/followups'
    | '/applications/timeline'
    | '/batch/$id'
    | '/cover-letters/builder'
    | '/jobs/$jobId'
    | '/jobs/history'
    | '/jobs/import'
    | '/resumes/$id'
    | '/resumes/builder'
    | '/resumes/profile-editor'
    | '/resumes/profiles'
    | '/settings/ai'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/resume'
    | '/analytics/'
    | '/applications/'
    | '/cover-letters/'
    | '/jobs/'
    | '/resumes/'
    | '/settings/'
    | '/resumes/$id/editor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/logout'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/verify-email'
    | '/batch'
    | '/dashboard'
    | '/match'
    | '/notifications'
    | '/ranking'
    | '/analytics/market'
    | '/analytics/skills'
    | '/applications/$id'
    | '/applications/followups'
    | '/applications/timeline'
    | '/batch/$id'
    | '/cover-letters/builder'
    | '/jobs/$jobId'
    | '/jobs/history'
    | '/jobs/import'
    | '/resumes/$id'
    | '/resumes/builder'
    | '/resumes/profile-editor'
    | '/resumes/profiles'
    | '/settings/ai'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/resume'
    | '/analytics'
    | '/applications'
    | '/cover-letters'
    | '/jobs'
    | '/resumes'
    | '/settings'
    | '/resumes/$id/editor'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/logout'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/verify-email'
    | '/_app/analytics'
    | '/_app/applications'
    | '/_app/batch'
    | '/_app/cover-letters'
    | '/_app/dashboard'
    | '/_app/jobs'
    | '/_app/match'
    | '/_app/notifications'
    | '/_app/ranking'
    | '/_app/resumes'
    | '/_app/settings'
    | '/_app/analytics/market'
    | '/_app/analytics/skills'
    | '/_app/applications/$id'
    | '/_app/applications/followups'
    | '/_app/applications/timeline'
    | '/_app/batch/$id'
    | '/_app/cover-letters/builder'
    | '/_app/jobs/$jobId'
    | '/_app/jobs/history'
    | '/_app/jobs/import'
    | '/_app/resumes/$id'
    | '/_app/resumes/builder'
    | '/_app/resumes/profile-editor'
    | '/_app/resumes/profiles'
    | '/_app/settings/ai'
    | '/_app/settings/notifications'
    | '/_app/settings/privacy'
    | '/_app/settings/resume'
    | '/_app/analytics/'
    | '/_app/applications/'
    | '/_app/cover-letters/'
    | '/_app/jobs/'
    | '/_app/resumes/'
    | '/_app/settings/'
    | '/_app/resumes/$id/editor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resumes': {
      id: '/_app/resumes'
      path: '/resumes'
      fullPath: '/resumes'
      preLoaderRoute: typeof AppResumesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ranking': {
      id: '/_app/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AppRankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/match': {
      id: '/_app/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof AppMatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cover-letters': {
      id: '/_app/cover-letters'
      path: '/cover-letters'
      fullPath: '/cover-letters'
      preLoaderRoute: typeof AppCoverLettersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/batch': {
      id: '/_app/batch'
      path: '/batch'
      fullPath: '/batch'
      preLoaderRoute: typeof AppBatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/applications': {
      id: '/_app/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/resumes/': {
      id: '/_app/resumes/'
      path: '/'
      fullPath: '/resumes/'
      preLoaderRoute: typeof AppResumesIndexRouteImport
      parentRoute: typeof AppResumesRoute
    }
    '/_app/jobs/': {
      id: '/_app/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AppJobsIndexRouteImport
      parentRoute: typeof AppJobsRoute
    }
    '/_app/cover-letters/': {
      id: '/_app/cover-letters/'
      path: '/'
      fullPath: '/cover-letters/'
      preLoaderRoute: typeof AppCoverLettersIndexRouteImport
      parentRoute: typeof AppCoverLettersRoute
    }
    '/_app/applications/': {
      id: '/_app/applications/'
      path: '/'
      fullPath: '/applications/'
      preLoaderRoute: typeof AppApplicationsIndexRouteImport
      parentRoute: typeof AppApplicationsRoute
    }
    '/_app/analytics/': {
      id: '/_app/analytics/'
      path: '/'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AppAnalyticsIndexRouteImport
      parentRoute: typeof AppAnalyticsRoute
    }
    '/_app/settings/resume': {
      id: '/_app/settings/resume'
      path: '/resume'
      fullPath: '/settings/resume'
      preLoaderRoute: typeof AppSettingsResumeRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/privacy': {
      id: '/_app/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof AppSettingsPrivacyRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/ai': {
      id: '/_app/settings/ai'
      path: '/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof AppSettingsAiRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/resumes/profiles': {
      id: '/_app/resumes/profiles'
      path: '/profiles'
      fullPath: '/resumes/profiles'
      preLoaderRoute: typeof AppResumesProfilesRouteImport
      parentRoute: typeof AppResumesRoute
    }
    '/_app/resumes/profile-editor': {
      id: '/_app/resumes/profile-editor'
      path: '/profile-editor'
      fullPath: '/resumes/profile-editor'
      preLoaderRoute: typeof AppResumesProfileEditorRouteImport
      parentRoute: typeof AppResumesRoute
    }
    '/_app/resumes/builder': {
      id: '/_app/resumes/builder'
      path: '/builder'
      fullPath: '/resumes/builder'
      preLoaderRoute: typeof AppResumesBuilderRouteImport
      parentRoute: typeof AppResumesRoute
    }
    '/_app/resumes/$id': {
      id: '/_app/resumes/$id'
      path: '/$id'
      fullPath: '/resumes/$id'
      preLoaderRoute: typeof AppResumesIdRouteImport
      parentRoute: typeof AppResumesRoute
    }
    '/_app/jobs/import': {
      id: '/_app/jobs/import'
      path: '/import'
      fullPath: '/jobs/import'
      preLoaderRoute: typeof AppJobsImportRouteImport
      parentRoute: typeof AppJobsRoute
    }
    '/_app/jobs/history': {
      id: '/_app/jobs/history'
      path: '/history'
      fullPath: '/jobs/history'
      preLoaderRoute: typeof AppJobsHistoryRouteImport
      parentRoute: typeof AppJobsRoute
    }
    '/_app/jobs/$jobId': {
      id: '/_app/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AppJobsJobIdRouteImport
      parentRoute: typeof AppJobsRoute
    }
    '/_app/cover-letters/builder': {
      id: '/_app/cover-letters/builder'
      path: '/builder'
      fullPath: '/cover-letters/builder'
      preLoaderRoute: typeof AppCoverLettersBuilderRouteImport
      parentRoute: typeof AppCoverLettersRoute
    }
    '/_app/batch/$id': {
      id: '/_app/batch/$id'
      path: '/$id'
      fullPath: '/batch/$id'
      preLoaderRoute: typeof AppBatchIdRouteImport
      parentRoute: typeof AppBatchRoute
    }
    '/_app/applications/timeline': {
      id: '/_app/applications/timeline'
      path: '/timeline'
      fullPath: '/applications/timeline'
      preLoaderRoute: typeof AppApplicationsTimelineRouteImport
      parentRoute: typeof AppApplicationsRoute
    }
    '/_app/applications/followups': {
      id: '/_app/applications/followups'
      path: '/followups'
      fullPath: '/applications/followups'
      preLoaderRoute: typeof AppApplicationsFollowupsRouteImport
      parentRoute: typeof AppApplicationsRoute
    }
    '/_app/applications/$id': {
      id: '/_app/applications/$id'
      path: '/$id'
      fullPath: '/applications/$id'
      preLoaderRoute: typeof AppApplicationsIdRouteImport
      parentRoute: typeof AppApplicationsRoute
    }
    '/_app/analytics/skills': {
      id: '/_app/analytics/skills'
      path: '/skills'
      fullPath: '/analytics/skills'
      preLoaderRoute: typeof AppAnalyticsSkillsRouteImport
      parentRoute: typeof AppAnalyticsRoute
    }
    '/_app/analytics/market': {
      id: '/_app/analytics/market'
      path: '/market'
      fullPath: '/analytics/market'
      preLoaderRoute: typeof AppAnalyticsMarketRouteImport
      parentRoute: typeof AppAnalyticsRoute
    }
    '/_app/resumes/$id/editor': {
      id: '/_app/resumes/$id/editor'
      path: '/editor'
      fullPath: '/resumes/$id/editor'
      preLoaderRoute: typeof AppResumesIdEditorRouteImport
      parentRoute: typeof AppResumesIdRoute
    }
  }
}

interface AppAnalyticsRouteChildren {
  AppAnalyticsMarketRoute: typeof AppAnalyticsMarketRoute
  AppAnalyticsSkillsRoute: typeof AppAnalyticsSkillsRoute
  AppAnalyticsIndexRoute: typeof AppAnalyticsIndexRoute
}

const AppAnalyticsRouteChildren: AppAnalyticsRouteChildren = {
  AppAnalyticsMarketRoute: AppAnalyticsMarketRoute,
  AppAnalyticsSkillsRoute: AppAnalyticsSkillsRoute,
  AppAnalyticsIndexRoute: AppAnalyticsIndexRoute,
}

const AppAnalyticsRouteWithChildren = AppAnalyticsRoute._addFileChildren(
  AppAnalyticsRouteChildren,
)

interface AppApplicationsRouteChildren {
  AppApplicationsIdRoute: typeof AppApplicationsIdRoute
  AppApplicationsFollowupsRoute: typeof AppApplicationsFollowupsRoute
  AppApplicationsTimelineRoute: typeof AppApplicationsTimelineRoute
  AppApplicationsIndexRoute: typeof AppApplicationsIndexRoute
}

const AppApplicationsRouteChildren: AppApplicationsRouteChildren = {
  AppApplicationsIdRoute: AppApplicationsIdRoute,
  AppApplicationsFollowupsRoute: AppApplicationsFollowupsRoute,
  AppApplicationsTimelineRoute: AppApplicationsTimelineRoute,
  AppApplicationsIndexRoute: AppApplicationsIndexRoute,
}

const AppApplicationsRouteWithChildren = AppApplicationsRoute._addFileChildren(
  AppApplicationsRouteChildren,
)

interface AppBatchRouteChildren {
  AppBatchIdRoute: typeof AppBatchIdRoute
}

const AppBatchRouteChildren: AppBatchRouteChildren = {
  AppBatchIdRoute: AppBatchIdRoute,
}

const AppBatchRouteWithChildren = AppBatchRoute._addFileChildren(
  AppBatchRouteChildren,
)

interface AppCoverLettersRouteChildren {
  AppCoverLettersBuilderRoute: typeof AppCoverLettersBuilderRoute
  AppCoverLettersIndexRoute: typeof AppCoverLettersIndexRoute
}

const AppCoverLettersRouteChildren: AppCoverLettersRouteChildren = {
  AppCoverLettersBuilderRoute: AppCoverLettersBuilderRoute,
  AppCoverLettersIndexRoute: AppCoverLettersIndexRoute,
}

const AppCoverLettersRouteWithChildren = AppCoverLettersRoute._addFileChildren(
  AppCoverLettersRouteChildren,
)

interface AppJobsRouteChildren {
  AppJobsJobIdRoute: typeof AppJobsJobIdRoute
  AppJobsHistoryRoute: typeof AppJobsHistoryRoute
  AppJobsImportRoute: typeof AppJobsImportRoute
  AppJobsIndexRoute: typeof AppJobsIndexRoute
}

const AppJobsRouteChildren: AppJobsRouteChildren = {
  AppJobsJobIdRoute: AppJobsJobIdRoute,
  AppJobsHistoryRoute: AppJobsHistoryRoute,
  AppJobsImportRoute: AppJobsImportRoute,
  AppJobsIndexRoute: AppJobsIndexRoute,
}

const AppJobsRouteWithChildren =
  AppJobsRoute._addFileChildren(AppJobsRouteChildren)

interface AppResumesIdRouteChildren {
  AppResumesIdEditorRoute: typeof AppResumesIdEditorRoute
}

const AppResumesIdRouteChildren: AppResumesIdRouteChildren = {
  AppResumesIdEditorRoute: AppResumesIdEditorRoute,
}

const AppResumesIdRouteWithChildren = AppResumesIdRoute._addFileChildren(
  AppResumesIdRouteChildren,
)

interface AppResumesRouteChildren {
  AppResumesIdRoute: typeof AppResumesIdRouteWithChildren
  AppResumesBuilderRoute: typeof AppResumesBuilderRoute
  AppResumesProfileEditorRoute: typeof AppResumesProfileEditorRoute
  AppResumesProfilesRoute: typeof AppResumesProfilesRoute
  AppResumesIndexRoute: typeof AppResumesIndexRoute
}

const AppResumesRouteChildren: AppResumesRouteChildren = {
  AppResumesIdRoute: AppResumesIdRouteWithChildren,
  AppResumesBuilderRoute: AppResumesBuilderRoute,
  AppResumesProfileEditorRoute: AppResumesProfileEditorRoute,
  AppResumesProfilesRoute: AppResumesProfilesRoute,
  AppResumesIndexRoute: AppResumesIndexRoute,
}

const AppResumesRouteWithChildren = AppResumesRoute._addFileChildren(
  AppResumesRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsAiRoute: typeof AppSettingsAiRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsPrivacyRoute: typeof AppSettingsPrivacyRoute
  AppSettingsResumeRoute: typeof AppSettingsResumeRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAiRoute: AppSettingsAiRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsPrivacyRoute: AppSettingsPrivacyRoute,
  AppSettingsResumeRoute: AppSettingsResumeRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRouteWithChildren
  AppApplicationsRoute: typeof AppApplicationsRouteWithChildren
  AppBatchRoute: typeof AppBatchRouteWithChildren
  AppCoverLettersRoute: typeof AppCoverLettersRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppJobsRoute: typeof AppJobsRouteWithChildren
  AppMatchRoute: typeof AppMatchRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppRankingRoute: typeof AppRankingRoute
  AppResumesRoute: typeof AppResumesRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRouteWithChildren,
  AppApplicationsRoute: AppApplicationsRouteWithChildren,
  AppBatchRoute: AppBatchRouteWithChildren,
  AppCoverLettersRoute: AppCoverLettersRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppJobsRoute: AppJobsRouteWithChildren,
  AppMatchRoute: AppMatchRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppRankingRoute: AppRankingRoute,
  AppResumesRoute: AppResumesRouteWithChildren,
  AppSettingsRoute: AppSettingsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
