"""add_learning_and_progress_models

Revision ID: bf8fac80317f
Revises: 20260917_007
Create Date: 2026-09-17 18:19:09.185752+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20260917_008'
down_revision: Union[str, None] = '20260917_007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('access_type', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_resources_skill_id'), ['skill_id'], unique=False)

    op.create_table('project_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('prerequisites', sa.JSON(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('acceptance_criteria', sa.JSON(), nullable=False),
    sa.Column('evidence_artifacts', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('skill_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_learning_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('project_template_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('minutes_spent', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('(resource_id IS NOT NULL AND project_template_id IS NULL) OR (resource_id IS NULL AND project_template_id IS NOT NULL)', name='check_resource_or_project'),
    sa.ForeignKeyConstraint(['project_template_id'], ['project_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['learning_resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_learning_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_learning_progress_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('skill_taxonomy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canonical_key', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    op.execute("UPDATE skill_taxonomy SET active = true, canonical_key = name WHERE canonical_key IS NULL")

    with op.batch_alter_table('skill_taxonomy', schema=None) as batch_op:
        batch_op.alter_column('canonical_key', existing_type=sa.String(length=100), nullable=False)
        batch_op.alter_column('active', existing_type=sa.Boolean(), nullable=False)
        batch_op.create_index(batch_op.f('ix_skill_taxonomy_canonical_key'), ['canonical_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill_taxonomy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_taxonomy_canonical_key'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('active')
        batch_op.drop_column('canonical_key')

    with op.batch_alter_table('user_learning_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_learning_progress_user_id'))

    op.drop_table('user_learning_progress')
    op.drop_table('project_templates')
    with op.batch_alter_table('learning_resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_resources_skill_id'))

    op.drop_table('learning_resources')
    # ### end Alembic commands ###

