"""add_profile_tables

Revision ID: 3f487ed6cb6e
Revises: 4f0218ad2e0c
Create Date: 2026-06-22 20:05:31.427843+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f487ed6cb6e'
down_revision: Union[str, None] = '4f0218ad2e0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
